server {
       listen      80;
       listen      [::]:80;
       server_name test143.loc;
	   root /var/www/app/public;
	   index index.php index.html index.htm;
	   #размер буфера для тела запроса
	   client_body_buffer_size 60K;
	   #размер буфера для заголовка;
	   client_header_buffer_size 4K;
	   #максимальное количество и размер буфера для чтения большого заголовка.upload_max_filesize post_max_size значение должно соответствовать в php.ini
	   client_max_body_size 12m;
	   large_client_header_buffers 4 64k;
	     location / {
        # try to serve file directly, fallback to index.php
          try_files $uri /index.php$is_args$args;
         }

	    location ~ ^/index\.php(/|$) {
        fastcgi_pass php-fpm:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
		# 1. Увеличиваем буферы FastCGI (обязательно кратно 4k)
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 128k;
        fastcgi_busy_buffers_size 128k;
        # 2. ОГРАНИЧИВАЕМ разм перед заголов в PHP
        # Если 64k+, будет ошибка "record too big"
        # Мы огран буфер вывода, чтобы Nginx нарезал данные
        fastcgi_limit_rate 0;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root/$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        internal;
    }
       # this prevents access to other php files you don't want to be accessible.
    location ~ \.php$ {
        return 404;
    }
}


